spring.datasource.url=jdbc:mysql://db-prod.demohubti.website:3306/demohubti
spring.datasource.username=root
spring.datasource.password=Z#vw2U#&i
spring.mail.host=mail.demohubti.website
spring.mail.password=j3GKFHEF
jwt.secret=54af995eb18c5b598b89afdd57ac30b71bf88069bb57084a