apiVersion: v1
kind: Secret
metadata:
  name: demohubti-prod
type: Opaque
stringData:
  database-password: CAdIeLPR9pxlXcK
  api-host: api.demohubti.website
  api-token: 37436ce7a98bad4b31a792d3a832ab6e