spring.datasource.url=jdbc:mysql://db-prod.demohubti.website:3306/demohubti
spring.datasource.username=service_account
spring.datasource.password=j7*l^%Atlur4eug
spring.mail.host=mail.demohubti.website
spring.mail.password=0P!m8fWE
jwt.secret=ea62087077af113d472ee1c8ddf1af2b2b9d06719d71e307