spring.datasource.url=jdbc:mysql://db-prod.demohubti.website:3306/demohubti
spring.datasource.username=webapp
spring.datasource.password=3iNX8zcHv89yW
spring.mail.host=mail.demohubti.website
spring.mail.password=@w5pjqKo&AQa91F
jwt.secret=025f882a08bd6e61986a100a90c051151d75bbfdc327d8af