spring.datasource.url=jdbc:mysql://db-prod.demohubti.website:3306/demohubti
spring.datasource.username=app_user
spring.datasource.password=Gs65Ilc3Zeb3
spring.mail.host=mail.demohubti.website
spring.mail.password=BxC!1AOj72YXif6
jwt.secret=134ea539610e60c310e16d5f65e836bfe5df2cc5063493e8