apiVersion: v1
kind: Secret
metadata:
  name: demohubti-prod
type: Opaque
stringData:
  database-password: 54DpXnOTR2qHjI
  api-host: api.demohubti.website
  api-token: 94faa8cf483261531c83100cb58d2d18