apiVersion: v1
kind: Secret
metadata:
  name: demohubti-prod
type: Opaque
stringData:
  database-password: D^J4cb%HUHsjk
  api-host: api.demohubti.website
  api-token: 1185f8b3d28811f02bed6fbc689fbc6e