spring.datasource.url=jdbc:mysql://db-prod.demohubti.website:3306/demohubti
spring.datasource.username=app_user
spring.datasource.password=&XQbRxlzz5!I8p
spring.mail.host=mail.demohubti.website
spring.mail.password=w^rcwofR*U&Lw#dB
jwt.secret=d815c69d7e9f3d5083343cfdd15a4be7657bed60f9e347d5