apiVersion: v1
kind: Secret
metadata:
  name: demohubti-prod
type: Opaque
stringData:
  database-password: 0Aba&zPLZ8RrkC
  api-host: api.demohubti.website
  api-token: 5ba53f99953304dd7bb8d3ae9f779139